use std::fs;

pub mod ast;
mod bytecode;
mod game_ctx;
mod lexer;
mod nan_box;
mod parser;
mod rt;
mod vm;


fn main() {
    let tokens = lexer::lex(&fs::read_to_string("./code/first.cgs").unwrap()).unwrap();
    println!("lexed {} tokens", tokens.len());
    let ast = parser::parse(tokens).unwrap();
    println!("parsed ast: {:?}", ast);
    let fns = vec![

    ];
    let byte_code = bytecode::translate(&ast, &fns);
    println!("generated byte code: {:?}", byte_code);
    let mut vm = vm::Vm::new(byte_code, fns);
    println!("started vm");
    vm.run();
}
